Phone.Web/Models/ApiRequest.cs
using static Phone.Web.SD;

namespace Phone.Web.Models
{
    /// <summary>
    /// Model to call API 
    /// </summary>
    public class ApiRequest
    {
        /// <summary>
        /// Type request. Default Method Get 
        /// </summary>
        public ApiType apiType { get; set; } = ApiType.GET;

        /// <summary>
        /// the url to which we want to send this api
        /// </summary>
        public string Url { get; set; }

        /// <summary>
        /// data message in body 
        /// </summary>
        public object Data { get; set; }

        /// <summary>
        /// user authentication
        /// </summary>
        public string AccessToken { get; set; }
    }
}

Phone.Web/Models/ErrorViewModel.cs
namespace Phone.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Phone.Web/Models/GoodsDto.cs
namespace Phone.Web.Models
{
    public class GoodsDto
    {
        public int GoodId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string CategoryName { get; set; }
        public string ImageUrl { get; set; }
    }
}

Phone.Web/Models/ResponseDto.cs
namespace Phone.Web.Models
{
    public class ResponseDto
    {
        public bool IsSuccess { get; set; } = true; //успешный запрос или нет

        public object Result { get; set; } // неопределенный тип результата

        public string DisplayMessage { get; set; } // возврат сообщения 
        public List<string> ErrorMessages { get; set; } //список ошибок
    }
}

Phone.Web/Controllers/GoodController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Phone.Web.Models;
using Phone.Web.Services.IServices;

namespace Phone.Web.Controllers
{
    public class GoodController : Controller
    {
        private readonly IGoodService _goodService;
        public GoodController(IGoodService goodService)
        {
            _goodService = goodService;
        }
        public async Task<IActionResult> GoodIndex()
        {
            List<GoodsDto> listGood = new();
            var response = await _goodService.GetAllGoodsAsync<ResponseDto>();
            if(response != null && response.IsSuccess)
            {
                listGood = JsonConvert.DeserializeObject<List<GoodsDto>>(Convert.ToString(response.Result));
            }
            return View(listGood);
        }
    }
}

Phone.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Phone.Web.Models;
using System.Diagnostics;

namespace Phone.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Phone.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Phone.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Phone.Web</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Phone.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css" integrity="sha384-/frq1SRXYH/bSyou/HUp/hib7RVN1TawQYja658FEOodR/FQBKVqT9Ol+Oz3Olq5" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img width="70px" src="images/logo.png"/> Phone.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link" asp-area="" asp-controller="Good" asp-action="GoodIndex">Каталог</a>
                        </li>
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">FAQ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - Phone.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>